### ISSUE TITLE
It's a security vulnerability to store your ssl private keys at rest unencrypted

### ISSUE THREAD

**Issue by jhg03a** [thias/puppet-tlsfiles#4]
It's a bad idea to store your private keys at rest on your puppet server in plaintext (or even worse in your source control repository).

**Comment by thias** [comment]
I totally agree. This module is probably not a good choice if that's a concern, though, as it's definitely focused at tightly controlled environments where the people with root access to all servers (puppet masters included) are the only ones with access to the repository where tls files are stored.
